app/chat/__init__.py
from bson import ObjectId
from .dbo import Chat, Message

def spawn_chat(u1 : ObjectId, u2 : ObjectId):
    item = Chat.get_for_ids(u1, u2)
    if not item:
        item = Chat(u1, u2)
    return item

app/chat/routes.py
from flask import Blueprint, render_template
from flask_jwt_extended import jwt_required, current_user
from .dbo import Chat

CHAT = Blueprint("chat", __name__)

@CHAT.route("/chat")
@jwt_required
def view():
    ownChats = pendingChats = Chat.get({"authors" : {"$elemMatch" : {"user" : current_user._id, "pending" : True}}})
    if not ownChats:
        ownChats = []
    else:
        if not isinstance(ownChats, list):
            ownChats = [ownChats]
    return render_template("alerts/pages/chat.html", ownChats=ownChats, user_id=current_user._id)

app/notifications/routes.py
from flask import Blueprint, render_template
from flask_jwt_extended import jwt_required, current_user
import time
NOTIFICATION = Blueprint("notifications", __name__)

@NOTIFICATION.route("/notifications")
@jwt_required
def notif():
	from app.notifications import UserNotifications
	alerts = UserNotifications.get_unread(current_user)
	for i in alerts:
		i.read = True
		i.save()
	return render_template("alerts/pages/alerts.html",alerts=alerts)

@NOTIFICATION.route("/messages")
def messages():
	pass


@NOTIFICATION.route("/notifications/older")
@jwt_required
def old_notif():
	from app.notifications import UserNotifications
	alerts = UserNotifications.get_read(current_user)
	return render_template("alerts/pages/alerts.html",alerts=alerts, old=True)

app/templates/alerts/pages/alerts.html
{% extends 'alerts/template.html' %}
{%block page_items%}
	{% if alerts %}
		{% for alert in alerts %}
			{% include 'alerts/parts/notification.html' %}
		{% endfor %}
	{% else %}
		<div class="empty"></div>
		<span class="no_alerts" data-text="No alerts here">OP</span>
	{% endif %}
	{% if not old %}
		<a href="{{url_for('notifications.old_notif')}}">Old notifications</a>
	{% endif %}
{%endblock%}

app/templates/alerts/pages/chat.html
{% extends 'alerts/template.html' %}
{%block page_items%}
<script>
	const user_id = "{{user_id}}"
</script>
<section class="chat">
	{% include 'alerts/parts/chat_bar.html' %}
	{% include 'alerts/parts/chat_space.html' %}
	
</section>
<link rel="stylesheet" type="text/css" media="screen" href=" {{ url_for('static', filename='css/chat.css', _external=True) }} " />
{%endblock%}